version: "2"

services:
  go_build:
    build: ./GODOCK
    volumes:
      - ./shared:/shared
      - ./go/src:/go/src
    working_dir: /go/src/go_app
    command: go build -o /shared/main .

  go_run:
    build: ./GODOCK
    volumes:
      - ./go/src:/go/src
    working_dir: /go/src/go_app
    command: go run main.go

  bin_run:
    build: ./GODOCK
    volumes:
      - ./shared:/shared
    working_dir: /shared
    command: ./main

  go_api:
    build: ./GODOCK
    volumes:
      - ./shared:/shared
      - ./go/src:/go/src
    working_dir: /shared/api-test/
    command: go build -o /shared/go_api .
    command: /shared/go_api
    ports:
      - "8080:8080"
